# Generated by Django 4.0.4 on 2022-04-17 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('secret_key', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('desc', models.TextField(default='')),
                ('valid', models.BooleanField(default=False)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=1024)),
                ('desc', models.TextField(default='')),
                ('valid', models.BooleanField(default=False)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Queued'), (1, 'Downloading'), (2, 'Deploying'), (3, 'Finished'), (4, 'Failed')], default=0)),
                ('source_type', models.IntegerField(choices=[(0, 'GitHub Actions')])),
                ('data', models.TextField(default='')),
                ('source', models.TextField(default='')),
                ('message', models.TextField(default='')),
                ('target_name', models.CharField(max_length=64)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('finish_time', models.DateTimeField()),
                ('creator_ip', models.CharField(default='', max_length=64)),
            ],
        ),
    ]
